[project]
name = "enhanced-de-prompt-engineering"
version = "0.1.0"
description = "A set of tasks to practice prompt engineering for Data Engineering use cases."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
