version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: de-prompt-pg
    environment:
      POSTGRES_DB: de_test
      POSTGRES_USER: de_test
      POSTGRES_PASSWORD: de_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U de_test -d de_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # Uncomment to persist data between runs
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
